// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: tracelens.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Tracelens.Proto.V1 {
  public static partial class DataService
  {
    static readonly string __ServiceName = "tracelens.proto.v1.DataService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tracelens.Proto.V1.GetSearchDataRequest> __Marshaller_tracelens_proto_v1_GetSearchDataRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tracelens.Proto.V1.GetSearchDataRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tracelens.Proto.V1.GetSearchDataResponse> __Marshaller_tracelens_proto_v1_GetSearchDataResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tracelens.Proto.V1.GetSearchDataResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tracelens.Proto.V1.GetValuesForTagRequest> __Marshaller_tracelens_proto_v1_GetValuesForTagRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tracelens.Proto.V1.GetValuesForTagRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tracelens.Proto.V1.GetValuesForTagResponse> __Marshaller_tracelens_proto_v1_GetValuesForTagResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tracelens.Proto.V1.GetValuesForTagResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tracelens.Proto.V1.SearchTracesRequest> __Marshaller_tracelens_proto_v1_SearchTracesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tracelens.Proto.V1.SearchTracesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tracelens.Proto.V1.SearchTracesResponse> __Marshaller_tracelens_proto_v1_SearchTracesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tracelens.Proto.V1.SearchTracesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tracelens.Proto.V1.GetSnapshotRequest> __Marshaller_tracelens_proto_v1_GetSnapshotRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tracelens.Proto.V1.GetSnapshotRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tracelens.Proto.V1.GetSnapshotResponse> __Marshaller_tracelens_proto_v1_GetSnapshotResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tracelens.Proto.V1.GetSnapshotResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tracelens.Proto.V1.GetServiceMapComponentsRequest> __Marshaller_tracelens_proto_v1_GetServiceMapComponentsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tracelens.Proto.V1.GetServiceMapComponentsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tracelens.Proto.V1.GetServiceMapComponentsResponse> __Marshaller_tracelens_proto_v1_GetServiceMapComponentsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tracelens.Proto.V1.GetServiceMapComponentsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tracelens.Proto.V1.GetComponentMetadataRequest> __Marshaller_tracelens_proto_v1_GetComponentMetadataRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tracelens.Proto.V1.GetComponentMetadataRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tracelens.Proto.V1.GetComponentMetadataResponse> __Marshaller_tracelens_proto_v1_GetComponentMetadataResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tracelens.Proto.V1.GetComponentMetadataResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tracelens.Proto.V1.SetComponentMetadataRequest> __Marshaller_tracelens_proto_v1_SetComponentMetadataRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tracelens.Proto.V1.SetComponentMetadataRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tracelens.Proto.V1.SetComponentMetadataResponse> __Marshaller_tracelens_proto_v1_SetComponentMetadataResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tracelens.Proto.V1.SetComponentMetadataResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tracelens.Proto.V1.GetMetadataForComponentRequest> __Marshaller_tracelens_proto_v1_GetMetadataForComponentRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tracelens.Proto.V1.GetMetadataForComponentRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tracelens.Proto.V1.GetMetadataForComponentResponse> __Marshaller_tracelens_proto_v1_GetMetadataForComponentResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tracelens.Proto.V1.GetMetadataForComponentResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tracelens.Proto.V1.GetMetricNamesRequest> __Marshaller_tracelens_proto_v1_GetMetricNamesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tracelens.Proto.V1.GetMetricNamesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tracelens.Proto.V1.GetMetricNamesResponse> __Marshaller_tracelens_proto_v1_GetMetricNamesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tracelens.Proto.V1.GetMetricNamesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tracelens.Proto.V1.GetMetricRequest> __Marshaller_tracelens_proto_v1_GetMetricRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tracelens.Proto.V1.GetMetricRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tracelens.Proto.V1.GetMetricResponse> __Marshaller_tracelens_proto_v1_GetMetricResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tracelens.Proto.V1.GetMetricResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tracelens.Proto.V1.GetSearchDataRequest, global::Tracelens.Proto.V1.GetSearchDataResponse> __Method_GetSearchData = new grpc::Method<global::Tracelens.Proto.V1.GetSearchDataRequest, global::Tracelens.Proto.V1.GetSearchDataResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetSearchData",
        __Marshaller_tracelens_proto_v1_GetSearchDataRequest,
        __Marshaller_tracelens_proto_v1_GetSearchDataResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tracelens.Proto.V1.GetValuesForTagRequest, global::Tracelens.Proto.V1.GetValuesForTagResponse> __Method_GetValuesForTag = new grpc::Method<global::Tracelens.Proto.V1.GetValuesForTagRequest, global::Tracelens.Proto.V1.GetValuesForTagResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetValuesForTag",
        __Marshaller_tracelens_proto_v1_GetValuesForTagRequest,
        __Marshaller_tracelens_proto_v1_GetValuesForTagResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tracelens.Proto.V1.SearchTracesRequest, global::Tracelens.Proto.V1.SearchTracesResponse> __Method_SearchTraces = new grpc::Method<global::Tracelens.Proto.V1.SearchTracesRequest, global::Tracelens.Proto.V1.SearchTracesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SearchTraces",
        __Marshaller_tracelens_proto_v1_SearchTracesRequest,
        __Marshaller_tracelens_proto_v1_SearchTracesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tracelens.Proto.V1.GetSnapshotRequest, global::Tracelens.Proto.V1.GetSnapshotResponse> __Method_GetSnapshot = new grpc::Method<global::Tracelens.Proto.V1.GetSnapshotRequest, global::Tracelens.Proto.V1.GetSnapshotResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetSnapshot",
        __Marshaller_tracelens_proto_v1_GetSnapshotRequest,
        __Marshaller_tracelens_proto_v1_GetSnapshotResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tracelens.Proto.V1.GetServiceMapComponentsRequest, global::Tracelens.Proto.V1.GetServiceMapComponentsResponse> __Method_GetServiceMapComponents = new grpc::Method<global::Tracelens.Proto.V1.GetServiceMapComponentsRequest, global::Tracelens.Proto.V1.GetServiceMapComponentsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetServiceMapComponents",
        __Marshaller_tracelens_proto_v1_GetServiceMapComponentsRequest,
        __Marshaller_tracelens_proto_v1_GetServiceMapComponentsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tracelens.Proto.V1.GetComponentMetadataRequest, global::Tracelens.Proto.V1.GetComponentMetadataResponse> __Method_GetComponentMetadata = new grpc::Method<global::Tracelens.Proto.V1.GetComponentMetadataRequest, global::Tracelens.Proto.V1.GetComponentMetadataResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetComponentMetadata",
        __Marshaller_tracelens_proto_v1_GetComponentMetadataRequest,
        __Marshaller_tracelens_proto_v1_GetComponentMetadataResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tracelens.Proto.V1.SetComponentMetadataRequest, global::Tracelens.Proto.V1.SetComponentMetadataResponse> __Method_SetComponentMetadata = new grpc::Method<global::Tracelens.Proto.V1.SetComponentMetadataRequest, global::Tracelens.Proto.V1.SetComponentMetadataResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetComponentMetadata",
        __Marshaller_tracelens_proto_v1_SetComponentMetadataRequest,
        __Marshaller_tracelens_proto_v1_SetComponentMetadataResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tracelens.Proto.V1.GetMetadataForComponentRequest, global::Tracelens.Proto.V1.GetMetadataForComponentResponse> __Method_GetMetadataForComponent = new grpc::Method<global::Tracelens.Proto.V1.GetMetadataForComponentRequest, global::Tracelens.Proto.V1.GetMetadataForComponentResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetMetadataForComponent",
        __Marshaller_tracelens_proto_v1_GetMetadataForComponentRequest,
        __Marshaller_tracelens_proto_v1_GetMetadataForComponentResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tracelens.Proto.V1.GetMetricNamesRequest, global::Tracelens.Proto.V1.GetMetricNamesResponse> __Method_GetMetricNames = new grpc::Method<global::Tracelens.Proto.V1.GetMetricNamesRequest, global::Tracelens.Proto.V1.GetMetricNamesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetMetricNames",
        __Marshaller_tracelens_proto_v1_GetMetricNamesRequest,
        __Marshaller_tracelens_proto_v1_GetMetricNamesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tracelens.Proto.V1.GetMetricRequest, global::Tracelens.Proto.V1.GetMetricResponse> __Method_GetMetric = new grpc::Method<global::Tracelens.Proto.V1.GetMetricRequest, global::Tracelens.Proto.V1.GetMetricResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetMetric",
        __Marshaller_tracelens_proto_v1_GetMetricRequest,
        __Marshaller_tracelens_proto_v1_GetMetricResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Tracelens.Proto.V1.TracelensReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of DataService</summary>
    [grpc::BindServiceMethod(typeof(DataService), "BindService")]
    public abstract partial class DataServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tracelens.Proto.V1.GetSearchDataResponse> GetSearchData(global::Tracelens.Proto.V1.GetSearchDataRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tracelens.Proto.V1.GetValuesForTagResponse> GetValuesForTag(global::Tracelens.Proto.V1.GetValuesForTagRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tracelens.Proto.V1.SearchTracesResponse> SearchTraces(global::Tracelens.Proto.V1.SearchTracesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tracelens.Proto.V1.GetSnapshotResponse> GetSnapshot(global::Tracelens.Proto.V1.GetSnapshotRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tracelens.Proto.V1.GetServiceMapComponentsResponse> GetServiceMapComponents(global::Tracelens.Proto.V1.GetServiceMapComponentsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tracelens.Proto.V1.GetComponentMetadataResponse> GetComponentMetadata(global::Tracelens.Proto.V1.GetComponentMetadataRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tracelens.Proto.V1.SetComponentMetadataResponse> SetComponentMetadata(global::Tracelens.Proto.V1.SetComponentMetadataRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tracelens.Proto.V1.GetMetadataForComponentResponse> GetMetadataForComponent(global::Tracelens.Proto.V1.GetMetadataForComponentRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tracelens.Proto.V1.GetMetricNamesResponse> GetMetricNames(global::Tracelens.Proto.V1.GetMetricNamesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tracelens.Proto.V1.GetMetricResponse> GetMetric(global::Tracelens.Proto.V1.GetMetricRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for DataService</summary>
    public partial class DataServiceClient : grpc::ClientBase<DataServiceClient>
    {
      /// <summary>Creates a new client for DataService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DataServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for DataService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DataServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DataServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DataServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tracelens.Proto.V1.GetSearchDataResponse GetSearchData(global::Tracelens.Proto.V1.GetSearchDataRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSearchData(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tracelens.Proto.V1.GetSearchDataResponse GetSearchData(global::Tracelens.Proto.V1.GetSearchDataRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetSearchData, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tracelens.Proto.V1.GetSearchDataResponse> GetSearchDataAsync(global::Tracelens.Proto.V1.GetSearchDataRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSearchDataAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tracelens.Proto.V1.GetSearchDataResponse> GetSearchDataAsync(global::Tracelens.Proto.V1.GetSearchDataRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetSearchData, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tracelens.Proto.V1.GetValuesForTagResponse GetValuesForTag(global::Tracelens.Proto.V1.GetValuesForTagRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetValuesForTag(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tracelens.Proto.V1.GetValuesForTagResponse GetValuesForTag(global::Tracelens.Proto.V1.GetValuesForTagRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetValuesForTag, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tracelens.Proto.V1.GetValuesForTagResponse> GetValuesForTagAsync(global::Tracelens.Proto.V1.GetValuesForTagRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetValuesForTagAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tracelens.Proto.V1.GetValuesForTagResponse> GetValuesForTagAsync(global::Tracelens.Proto.V1.GetValuesForTagRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetValuesForTag, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tracelens.Proto.V1.SearchTracesResponse SearchTraces(global::Tracelens.Proto.V1.SearchTracesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SearchTraces(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tracelens.Proto.V1.SearchTracesResponse SearchTraces(global::Tracelens.Proto.V1.SearchTracesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SearchTraces, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tracelens.Proto.V1.SearchTracesResponse> SearchTracesAsync(global::Tracelens.Proto.V1.SearchTracesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SearchTracesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tracelens.Proto.V1.SearchTracesResponse> SearchTracesAsync(global::Tracelens.Proto.V1.SearchTracesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SearchTraces, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tracelens.Proto.V1.GetSnapshotResponse GetSnapshot(global::Tracelens.Proto.V1.GetSnapshotRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSnapshot(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tracelens.Proto.V1.GetSnapshotResponse GetSnapshot(global::Tracelens.Proto.V1.GetSnapshotRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetSnapshot, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tracelens.Proto.V1.GetSnapshotResponse> GetSnapshotAsync(global::Tracelens.Proto.V1.GetSnapshotRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSnapshotAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tracelens.Proto.V1.GetSnapshotResponse> GetSnapshotAsync(global::Tracelens.Proto.V1.GetSnapshotRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetSnapshot, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tracelens.Proto.V1.GetServiceMapComponentsResponse GetServiceMapComponents(global::Tracelens.Proto.V1.GetServiceMapComponentsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetServiceMapComponents(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tracelens.Proto.V1.GetServiceMapComponentsResponse GetServiceMapComponents(global::Tracelens.Proto.V1.GetServiceMapComponentsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetServiceMapComponents, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tracelens.Proto.V1.GetServiceMapComponentsResponse> GetServiceMapComponentsAsync(global::Tracelens.Proto.V1.GetServiceMapComponentsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetServiceMapComponentsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tracelens.Proto.V1.GetServiceMapComponentsResponse> GetServiceMapComponentsAsync(global::Tracelens.Proto.V1.GetServiceMapComponentsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetServiceMapComponents, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tracelens.Proto.V1.GetComponentMetadataResponse GetComponentMetadata(global::Tracelens.Proto.V1.GetComponentMetadataRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetComponentMetadata(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tracelens.Proto.V1.GetComponentMetadataResponse GetComponentMetadata(global::Tracelens.Proto.V1.GetComponentMetadataRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetComponentMetadata, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tracelens.Proto.V1.GetComponentMetadataResponse> GetComponentMetadataAsync(global::Tracelens.Proto.V1.GetComponentMetadataRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetComponentMetadataAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tracelens.Proto.V1.GetComponentMetadataResponse> GetComponentMetadataAsync(global::Tracelens.Proto.V1.GetComponentMetadataRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetComponentMetadata, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tracelens.Proto.V1.SetComponentMetadataResponse SetComponentMetadata(global::Tracelens.Proto.V1.SetComponentMetadataRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetComponentMetadata(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tracelens.Proto.V1.SetComponentMetadataResponse SetComponentMetadata(global::Tracelens.Proto.V1.SetComponentMetadataRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetComponentMetadata, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tracelens.Proto.V1.SetComponentMetadataResponse> SetComponentMetadataAsync(global::Tracelens.Proto.V1.SetComponentMetadataRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetComponentMetadataAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tracelens.Proto.V1.SetComponentMetadataResponse> SetComponentMetadataAsync(global::Tracelens.Proto.V1.SetComponentMetadataRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetComponentMetadata, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tracelens.Proto.V1.GetMetadataForComponentResponse GetMetadataForComponent(global::Tracelens.Proto.V1.GetMetadataForComponentRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetMetadataForComponent(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tracelens.Proto.V1.GetMetadataForComponentResponse GetMetadataForComponent(global::Tracelens.Proto.V1.GetMetadataForComponentRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetMetadataForComponent, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tracelens.Proto.V1.GetMetadataForComponentResponse> GetMetadataForComponentAsync(global::Tracelens.Proto.V1.GetMetadataForComponentRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetMetadataForComponentAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tracelens.Proto.V1.GetMetadataForComponentResponse> GetMetadataForComponentAsync(global::Tracelens.Proto.V1.GetMetadataForComponentRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetMetadataForComponent, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tracelens.Proto.V1.GetMetricNamesResponse GetMetricNames(global::Tracelens.Proto.V1.GetMetricNamesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetMetricNames(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tracelens.Proto.V1.GetMetricNamesResponse GetMetricNames(global::Tracelens.Proto.V1.GetMetricNamesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetMetricNames, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tracelens.Proto.V1.GetMetricNamesResponse> GetMetricNamesAsync(global::Tracelens.Proto.V1.GetMetricNamesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetMetricNamesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tracelens.Proto.V1.GetMetricNamesResponse> GetMetricNamesAsync(global::Tracelens.Proto.V1.GetMetricNamesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetMetricNames, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tracelens.Proto.V1.GetMetricResponse GetMetric(global::Tracelens.Proto.V1.GetMetricRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetMetric(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Tracelens.Proto.V1.GetMetricResponse GetMetric(global::Tracelens.Proto.V1.GetMetricRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetMetric, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tracelens.Proto.V1.GetMetricResponse> GetMetricAsync(global::Tracelens.Proto.V1.GetMetricRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetMetricAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Tracelens.Proto.V1.GetMetricResponse> GetMetricAsync(global::Tracelens.Proto.V1.GetMetricRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetMetric, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override DataServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DataServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(DataServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetSearchData, serviceImpl.GetSearchData)
          .AddMethod(__Method_GetValuesForTag, serviceImpl.GetValuesForTag)
          .AddMethod(__Method_SearchTraces, serviceImpl.SearchTraces)
          .AddMethod(__Method_GetSnapshot, serviceImpl.GetSnapshot)
          .AddMethod(__Method_GetServiceMapComponents, serviceImpl.GetServiceMapComponents)
          .AddMethod(__Method_GetComponentMetadata, serviceImpl.GetComponentMetadata)
          .AddMethod(__Method_SetComponentMetadata, serviceImpl.SetComponentMetadata)
          .AddMethod(__Method_GetMetadataForComponent, serviceImpl.GetMetadataForComponent)
          .AddMethod(__Method_GetMetricNames, serviceImpl.GetMetricNames)
          .AddMethod(__Method_GetMetric, serviceImpl.GetMetric).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, DataServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetSearchData, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tracelens.Proto.V1.GetSearchDataRequest, global::Tracelens.Proto.V1.GetSearchDataResponse>(serviceImpl.GetSearchData));
      serviceBinder.AddMethod(__Method_GetValuesForTag, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tracelens.Proto.V1.GetValuesForTagRequest, global::Tracelens.Proto.V1.GetValuesForTagResponse>(serviceImpl.GetValuesForTag));
      serviceBinder.AddMethod(__Method_SearchTraces, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tracelens.Proto.V1.SearchTracesRequest, global::Tracelens.Proto.V1.SearchTracesResponse>(serviceImpl.SearchTraces));
      serviceBinder.AddMethod(__Method_GetSnapshot, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tracelens.Proto.V1.GetSnapshotRequest, global::Tracelens.Proto.V1.GetSnapshotResponse>(serviceImpl.GetSnapshot));
      serviceBinder.AddMethod(__Method_GetServiceMapComponents, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tracelens.Proto.V1.GetServiceMapComponentsRequest, global::Tracelens.Proto.V1.GetServiceMapComponentsResponse>(serviceImpl.GetServiceMapComponents));
      serviceBinder.AddMethod(__Method_GetComponentMetadata, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tracelens.Proto.V1.GetComponentMetadataRequest, global::Tracelens.Proto.V1.GetComponentMetadataResponse>(serviceImpl.GetComponentMetadata));
      serviceBinder.AddMethod(__Method_SetComponentMetadata, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tracelens.Proto.V1.SetComponentMetadataRequest, global::Tracelens.Proto.V1.SetComponentMetadataResponse>(serviceImpl.SetComponentMetadata));
      serviceBinder.AddMethod(__Method_GetMetadataForComponent, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tracelens.Proto.V1.GetMetadataForComponentRequest, global::Tracelens.Proto.V1.GetMetadataForComponentResponse>(serviceImpl.GetMetadataForComponent));
      serviceBinder.AddMethod(__Method_GetMetricNames, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tracelens.Proto.V1.GetMetricNamesRequest, global::Tracelens.Proto.V1.GetMetricNamesResponse>(serviceImpl.GetMetricNames));
      serviceBinder.AddMethod(__Method_GetMetric, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tracelens.Proto.V1.GetMetricRequest, global::Tracelens.Proto.V1.GetMetricResponse>(serviceImpl.GetMetric));
    }

  }
}
#endregion
