name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore Asynkron.OtelReceiver.sln

      - name: Build
        run: dotnet build Asynkron.OtelReceiver.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test Asynkron.OtelReceiver.sln --no-build --configuration Release
